### ISSUE TITLE
Diorite and Andesite textures reversed?

### ISSUE THREAD

**Issue by BrisingrAerowing** [MinecraftModDevelopmentMods/MinecraftMineralogy#1]
It appears that the Diorite and Andesite textures are backwards (i.e. Diorite looks like andesite, and andesite looks like diorite).

Could that be checked?

**Comment by AfterRebelion** [comment]
Yes, they are.

**Comment by jriwanek** [comment]
Fixed in my local tree, which will be uploaded soon, along with many other fixes.
