### ISSUE TITLE
[1.12] Pumice makes mining/breaking sound of Gravel

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopmentMods/MinecraftMineralogy#13]
As per our discussion on Discord, Pumice is an igneous rock, so needs to have the stone breaking/mining sound event

**Comment by SkyBlade1978** [comment]
reading more about pumice, its a very lightweight low density stone

in the code cyano used the gravel (ground) sound on purpose, I'm happy to change the sound to stone though it probably would sound better, what do you think @jriwanek ?

**Comment by jriwanek** [comment]
Lets worry about it after everything else is sorted.

**Comment by SkyBlade1978** [comment]
I'm still of a mind that this isn't a bug (AFAIK it's always been like this), but happy to change it if you like @jriwanek ?  Otherwise can we close it?

**Comment by Morpheus1101** [comment]
I believe for what type of rock its meant to be, that the sound is incorrect

**Comment by SkyBlade1978** [comment]
Now fixed across 1.10 to 1.12
