### ISSUE TITLE
[1.12] Recipe for Cobblestone is incorrect

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopmentMods/MinecraftMineralogy#14]
Recipe apparently should be 2 Gravel + 2 Basalt

Current recipe is 2 stone + 2 gravel

**Comment by SkyBlade1978** [comment]
the 2 stone plus 2 gravel should work but also basalt and most other stones should work in place of vanilla stone, will need to fix

**Comment by SkyBlade1978** [comment]
@Morpheus1101 , did you get the chance to test this fix? Thanks.

**Comment by Morpheus1101** [comment]
This is fixed.
