### ISSUE TITLE
[1.12] basalt possibly not spawning?

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopmentMods/MinecraftMineralogy#15]
After having mined a great deal on y:49 and Y:11 i have not encountered any basalt as yet

**Comment by SkyBlade1978** [comment]
I thought I had seen it, will investigate

**Comment by SkyBlade1978** [comment]
![2017-11-25_13 52 01](https://user-images.githubusercontent.com/22159126/33231133-021b94b4-d1e8-11e7-8533-878f7fa9aee0.png)

Just created a new world, wend down, and basalt...

Either you've been unlucky looking for it, or possibly an interaction with another mod?  Although that seems unlikely if you're getting other igneous rocks spawning

**Comment by SkyBlade1978** [comment]
Which mods in your pack affect the world generation?  I know you have this, BOP, and what else?

**Comment by Morpheus1101** [comment]
BOP LostCities then COFHWorld for generation of ores
