### ISSUE TITLE
Various broken recipes

### ISSUE THREAD

**Issue by septemberWaves** [MinecraftModDevelopmentMods/MinecraftMineralogy#29]
Several of the decorative blocks have recipes which do not contain any inputs.

**Comment by SkyBlade1978** [comment]
Hi @eloquentJane I'm just finalising a new build so hopefully it will be ready to use soon, could you please let me have some more information which recipes your having problems with, and is this related to the recipe book?

**Comment by SkyBlade1978** [comment]
Also @eloquentJane  I forgot to ask, which version of minecraft and which version of mineralogy are you using?

**Comment by SkyBlade1978** [comment]
@jriwanek should we close this one? I don't know which recipes @eloquentJane is having trouble with..

**Comment by SkyBlade1978** [comment]
I'm pretty sure what @eloquentJane means is the same as issue #26 therefore I'll close this soon unless I hear otherwise
