### ISSUE TITLE
Bug: Non-standard OreDict of Limestone and possibly other blocks

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopmentMods/MinecraftMineralogy#42]
Limestone has the ore-dict of ``limestone`` whereas by convention it should have ``stoneLimestone`` as to integrate with mods such as Chisel. There may be other blocks but this was the first one I noticed.

**Comment by SkyBlade1978** [comment]
fixed in 1.12 branch, needs backporting to 1.10 and 1.11

**Comment by SkyBlade1978** [comment]
Now fixed across 1.10 to 1.12
