### ISSUE TITLE
[Request] [1.12.2] Deactivate all generation

### ISSUE THREAD

**Issue by Draskh** [MinecraftModDevelopmentMods/MinecraftMineralogy#62]
I would like to ask to add a option to remove all generation to save CPU load. I use CoFH World to generate the stone along with Underground Biomes. I don't need the generation of Mineralogy anymore but I cannot turn it of completly in the config.

**Comment by SkyBlade1978** [comment]
I'll add the option, it's a simple enough thing to do

**Comment by SkyBlade1978** [comment]
I've done the code for this for the 1.12 version, it should be in a build within a few days

**Comment by SkyBlade1978** [comment]
Complete in 1.12 latest build, needs back porting

**Comment by Draskh** [comment]
There is no config option in the latest build genrated in the config file. I also generated a new config file.

**Comment by Smartaros** [comment]
I would still like to be able to add the generation of vanilla stone together with rock genesis

**Comment by SkyBlade1978** [comment]
1.12? I thought that update had gone out to curse, I'll check it when I have a minute

**Comment by SkyBlade1978** [comment]
The option you're looking for is;
PLACE_MINERALOGY_ROCK

Switch it to false and the terrain generation should be off

**Comment by Draskh** [comment]
Yeah, I found it. Maybe I was a bit confused.
Thanks for adding the option.
