### ISSUE TITLE
Ability to disable mineralogy rocks and replace them with other mod blocks.

### ISSUE THREAD

**Issue by Waynekosimoto** [MinecraftModDevelopmentMods/MinecraftMineralogy#72]
I wanted to disable the mineralogy stone but retain the generation style by adding blocks to the whitelist, however that doesn't seem to work. Even if I retain the generation style and add all the mineralogy blocks to the blacklist while keeping what I want to the whitelist it doesn't do what I want.

**Comment by SkyBlade1978** [comment]
From what I recall last I looked at that part of the code, I don't think the whitelisting was ever finished or worked, yes this should be fixed.

**Comment by Waynekosimoto** [comment]
Any chance we can expect this in the near future?

**Comment by SkyBlade1978** [comment]
sorry it wasn't the near future, but I've fixed this on 1.10 now and in a few days expect to be porting to to 1.11 and 1.12 along with the new features

**Comment by SkyBlade1978** [comment]
This should be fixed in the new release
